language: node_js
node_js:
- '0.12'
- '0.10'
services:
- mongodb
notifications:
  slack:
    secure: fHop1QT6WlcI8QGG0tdrDKuSHDafXFupRyVbYSvql6mHwvN1YGuDaja7BuImwM1ozKwbdIM/O9sjhL5o9oFAmcjdq+Kjh3vpOhZ1pHuKUew2GmuZHZXU+sY6b6K2fNplE2zC8c84Z03LbG4gwqNTlRt/qRI3GT4fCTwEtt+7iAxC03qDRgRH/9OnPayYF0gUXPmtp0FIeAu0PUaLMMl/+MxOd/5ZPlE8v9gzeTv/BysdjzgWqau+SbQBlGG0YQxb8Vq4jlvykNEfYltx8SPVSkEEnBgeE9rYTfVn/urXG/YchKDdYtmSfLi1fXlPOFfUxhZAKLAAN2sQsPXlo847F4XZokN2A3761XXkmOUM+uRAYEsOMnkmqjDjP68Oi79Ccmo6lSlnoiZtBASo3WXeJVSnML8Sr4JtXOKrvsSsNycgSRDhj5K0XJlQPJlPwfzBMUH7gbC0z2RZo6/SLDYpVRN1tQW0F84aaQ6B9wyv0+eYw4lpylQqtwthZE9L4A4izNkVg+X9vmMeDwiykg7QvZjbmQPr5/DG3hsiWXvit6NHuJQw/nsk3F+9bYSo+9ADMh8kqVkTvfz07HUQnT7HTYIK2hk3S6T898Q0fBWDS5y2jLYG3Ya2H2tt0gyvvY5LZofLXLx0STUGS3mkqD2qIy7M53NQxYm2bhFflRsYMMM=
