language: node_js
node_js:
- '0.12'
- '0.10'
services:
- mongodb
notifications:
  email: false
  slack:
    secure: m9ZBq3AKJ9nfQj73nAweUKrBAkpILHWL5KHW5ZDe2Q+UK9VUno8Ul8IBYf35rUctTtUDdlrWDdhGjhz3a2d+e6DOoySh44dfLeu38L0Ho4v4SJdZTOMDh1iP9GwYI4GdtnTyBG4LO5a8N8te+STgEg9iyNhEcxIVCXz0DMem+vO2/q0fk3aR1n7OfkMshEKgifaqhrfggZYTnF1Mp9hPryO/dR5mDzGURhFrhEzWhiT49lLIRcLIJfup4BXynWlD6N0FS1D1oHMHcBxXahh0IAdhNQKfs1saHLSLwBzz/OO5/0tMmtlPErW/gMz0p7EEwdpf74CRNe71o0eEi5Y+ps4uQaKaWRLfvHoGqLoanMEzqgXP1OO8NcvXERJ9eCoSpEBYmj+tH7sgi2t0B2Qv1qJh8JZA2p3IbPG71nHRfyQVD7XcfJ5YwyRrggV0WhonuGDokd+3WLRcsT5YS6d76nQ1I/nGzfUagwhsyOLUm+IqEHzp3k4rnEmcwFbTTZzlxhXO5qbioDdNOTYaKulT/dQe6hwpM/MMpK/lvRDike24WLycbNpwmHE+bkLhbrvHraNrfbLCPFcLGSKstPxVjuRFVIzbokFW2TnQXS2lVNok3MXIt+fPM4OqUuRbdCpIHY40h8NFCsT0nYzeoM6HBbXLmekyFNjKvZmvCB++Udg=
deploy:
  provider: npm
  email: jason@centralping.com
  api_key:
    secure: Rv19U9aGHYVWOnoFLfFoJYtwmDHdga2gicEhH7snaiY4+KAoANNPhjGR5hXnXbYmTLrLoJ5rehfL1EG66/jnSjTNGJVha766Zkjra4aZ5gLROV6QCsrORV0uHiq0sGD5UfzpyMgpHEestc/UNpp5ijwTTExxPTzfUfm22/mK4CUJTrTLalya16Gb6cFc17qD3/B+VSm38/rtmvJyXA0svRVOtseBAn3d9RE7PWF6dteJnKiJckWkyeHx/lx2odaBJoGB6yD/p4JSaJ7KqwszMvdNa1kzDP0yhPVQUU/bdoXRyktnpL/HgZ50PPu/SU7JKEg/ic9V0X2ZjrGoHDTN+/+dVPuvK0nngiqQ94ak1yBFJwr98Z+OQIQWzw6ojT2dl/ToqciaH9tcKSdFAVAhnlM8pM//elmFITgSFswBKHhDO6Weikw1A2o2nkAqSY1H1/qgCot8D1G0y4wXsWbj6kv0Qp9kF7nI4vf/sDADfGPtqjH+21mEqdnUMuOEl/52RoCY4Mcn3OMi3mQT8MtTxJh/MSTILug3sGuHO70jwZd9a8nWSA/edBvul6UWS6qCZ8EeSpTgGbvJsPuUKAN9rgwBBtxp77YX9+y+K80Wh65YQBPEjFqDlgG2LhGTGdqtnY0k6ghgri7V7E+0rMd9E74Cc/IST2IukfPYLwd9rVM=
  on:
    tags: true
    repo: CentralPing/mongoose-plugin-modified
